apiVersion: v1
kind: Service
metadata:
  name: campus-portal
  labels:
    app: campus-portal
spec:
  type: ClusterIP
  selector:
    app: campus-portal
  ports:
    - name: http
      port: 80
      targetPort: 80
